/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Date;
import java.text.SimpleDateFormat;


/**
 *
 * @author aulia
 */
public class Laundry extends javax.swing.JFrame {
    
    DecimalFormat kursIndonesia;
    DecimalFormatSymbols formatRupiah;
    double nilai;
    
    //public void waktu(){
        //format Tanggal
    //    Date tgl = new Date();
    //    txtTglTransaksi.setDate(tgl);
    //}
   
    /**
     * Creates new form Laundry
     */
    public Laundry() {
        initComponents();
        
        //format rupiah
        kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        formatRupiah = new DecimalFormatSymbols();
        
        formatRupiah.setCurrencySymbol("Rp ");
        formatRupiah.setMonetaryDecimalSeparator(',');
        formatRupiah.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRupiah);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlamat = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblJmlPcs = new javax.swing.JLabel();
        lblNmCust = new javax.swing.JLabel();
        lblLayanan = new javax.swing.JLabel();
        lblBerat = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblEstAmbil = new javax.swing.JLabel();
        lblJemput = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNmCust = new javax.swing.JTextField();
        txtHp = new javax.swing.JTextField();
        txtJmlPcs = new javax.swing.JTextField();
        cmbLayanan = new javax.swing.JComboBox<>();
        txtEstAmbil = new com.toedter.calendar.JDateChooser();
        cmbBerat = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        cmbJemput = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();
        lblTglTransaksi = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTglTransaksi = new com.toedter.calendar.JDateChooser();
        lblKodeCust = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbKodeCust = new javax.swing.JComboBox<>();
        txtJemputHidden = new javax.swing.JTextField();
        txtKodeMembHidden = new javax.swing.JTextField();
        txtBeratHidden = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jumlah_data = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAlamat.setText("Alamat");

        lblHp.setText("No. HP");

        lblJmlPcs.setText("Jml Pakaian (pcs)");

        lblNmCust.setText("Nama Customer");

        lblLayanan.setText("Opsi Layanan ");

        lblBerat.setText("Berat Pakaian (kg)");

        lblHarga.setText("Harga per Kg");

        lblEstAmbil.setText("Est. Pengambilan");

        lblJemput.setText("Antar Jemput");

        lblTotal.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total Harga");

        jLabel11.setText(":");

        jLabel12.setText(":");

        jLabel13.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        jLabel16.setText(":");

        jLabel17.setText(":");

        jLabel18.setText(":");

        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setText(":");

        txtNmCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmCustActionPerformed(evt);
            }
        });
        txtNmCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNmCustKeyTyped(evt);
            }
        });

        txtHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHpActionPerformed(evt);
            }
        });
        txtHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHpKeyTyped(evt);
            }
        });

        txtJmlPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlPcsActionPerformed(evt);
            }
        });
        txtJmlPcs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlPcsKeyTyped(evt);
            }
        });

        cmbLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Layanan Kilat (4 Jam)", "Layanan Express (1 Hari)", "Layanan Biasa (2-3 Hari)" }));
        cmbLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLayananActionPerformed(evt);
            }
        });

        txtEstAmbil.setDateFormatString("d MMMM yyyy");

        cmbBerat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "1 Kg", "2 Kg", "3 Kg", "4 Kg", "5 Kg", "6 Kg", "7 Kg", "8 Kg", "9 Kg", "10 Kg" }));
        cmbBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBeratActionPerformed(evt);
            }
        });

        txtHarga.setEditable(false);
        txtHarga.setVisible(false);

        cmbJemput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Tidak", "Ya" }));
        cmbJemput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJemputActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.setVisible(false);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        lblJudul.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblJudul.setText("APLIKASI LAUNDRY BY TEAM 2");

        lblTglTransaksi.setText("Tgl. Transaksi");

        jLabel23.setText(":");

        txtTglTransaksi.setToolTipText("--Pilih Tanggal--");
        txtTglTransaksi.setDateFormatString("d MMMM yyyy");
        txtTglTransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTglTransaksiFocusGained(evt);
            }
        });

        lblKodeCust.setText("Kode Customer");

        jLabel21.setText(":");

        cmbKodeCust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Non. Member", "Member" }));
        cmbKodeCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKodeCustActionPerformed(evt);
            }
        });

        txtJemputHidden.setVisible(false);

        txtKodeMembHidden.setVisible(false);

        txtBeratHidden.setForeground(new java.awt.Color(153, 153, 255));
        txtBeratHidden.setVisible(false);

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        areaAlamat.setColumns(20);
        areaAlamat.setRows(5);
        jScrollPane1.setViewportView(areaAlamat);

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tgl. Ambil", "Nama Customer", "No. HP", "Layanan", "Total", "Jml", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelData.setVisible(true);
        jScrollPane2.setViewportView(tabelData);

        btnClear.setText("Isi Data Baru");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jumlah_data.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Rp 0,00");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Rp 0,00");

        lblTanggal.setText("yyyy-mm-dd");
        lblTanggal.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlah_data, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jScrollPane1))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(lblNmCust, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtNmCust)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblJmlPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtJmlPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtHp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(77, 77, 77)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblKodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbKodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(txtKodeMembHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEstAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblJemput, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbJemput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel20)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(20, 20, 20)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBeratHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJemputHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23))
                            .addComponent(txtTglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(cmbKodeCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNmCust, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtNmCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJmlPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtJmlPcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cmbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(cmbBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBeratHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodeMembHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEstAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(txtEstAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJemput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(cmbJemput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJemputHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        txtTglTransaksi.getAccessibleContext().setAccessibleName("--Pilih Tanggal--");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKodeCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKodeCustActionPerformed
        // TODO add your handling code here:
        String kodeCust;
        double discMember;
        
        //kodeCust = String.valueOf(cmbKodeCust.getSelectedIndex());
        
        if (cmbKodeCust.equals("Member")){
            discMember = 3000;
        }else{
            discMember = 0;
        }
        
        txtKodeMembHidden.setText(""+ discMember);
        
    }//GEN-LAST:event_cmbKodeCustActionPerformed

    private void cmbLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLayananActionPerformed
        // TODO add your handling code here:
        String layanan;
        double harga;
        
        layanan = String.valueOf(cmbLayanan.getSelectedItem());
        
        if (layanan.equals("Layanan Kilat (4 Jam)")){
            harga = 20000;
        }else if (layanan.equals("Layanan Express (1 Hari)")) {
            harga = 15000;    
        }else {
            harga = 10000;
        }
        
        txtHarga.setText(""+harga);
        
        //format rupiah
        nilai = Double.valueOf(txtHarga.getText());
        String result = kursIndonesia.format(nilai);
        jLabel3.setText(result.substring(0,result.length() - 3));
        //jLabel3.setText(kursIndonesia.format(nilai));

    }//GEN-LAST:event_cmbLayananActionPerformed

    private void cmbBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBeratActionPerformed
        // TODO add your handling code here:
        String berat;
        int hslBerat;
        
        berat = String.valueOf(cmbBerat.getSelectedItem());
        
        if (berat.equals("1 Kg")){
            hslBerat = 1;
        }else if (berat.equals("2 Kg")){
            hslBerat = 2;
        }else if (berat.equals("3 Kg")){
            hslBerat = 3;
        }else if (berat.equals("4 Kg")){
            hslBerat = 4;
        }else if (berat.equals("5 Kg")){
            hslBerat = 5;
        }else if (berat.equals("6 Kg")){
            hslBerat = 6;
        }else if (berat.equals("7 Kg")){
            hslBerat = 7;
        }else if (berat.equals("8 Kg")){
            hslBerat = 8;
        }else if (berat.equals("9 Kg")){
            hslBerat = 9;
        }else{
            hslBerat = 10;
        }
        
        txtBeratHidden.setText(""+hslBerat);
    }//GEN-LAST:event_cmbBeratActionPerformed

    private void cmbJemputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJemputActionPerformed
        // TODO add your handling code here:
        String antarJemput;
        double ongkir;
        
        antarJemput = String.valueOf(cmbJemput.getSelectedItem());
        
        if (antarJemput.equals("Tidak")){
            ongkir = 0;
        }else{
            ongkir = 5000;
        }
        
        txtJemputHidden.setText(""+ongkir);
        
    }//GEN-LAST:event_cmbJemputActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        double discMember, harga, ongkir, total;
        int hslBerat;
        
        if (txtNmCust.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masukan semua data", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (areaAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan semua data", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtHp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan semua data", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtJmlPcs.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan semua data", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if(txtKodeMembHidden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtBeratHidden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtJemputHidden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else if (txtKodeMembHidden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",
            JOptionPane.INFORMATION_MESSAGE); 
        } else{
            JOptionPane.showMessageDialog(null, "Data berhasil diproses", "Input Sukses",
            JOptionPane.INFORMATION_MESSAGE);
        }
        
        discMember = Double.parseDouble(txtKodeMembHidden.getText());
        harga = Double.parseDouble(txtHarga.getText());
        hslBerat = Integer.parseInt(txtBeratHidden.getText());
        ongkir = Double.parseDouble(txtJemputHidden.getText());
        
        total = (harga * hslBerat)  + ongkir - discMember;
        txtTotal.setText(""+total);
        
        //format rupiah
        nilai = Double.valueOf(txtTotal.getText());
        String result = kursIndonesia.format(nilai);
        jLabel4.setText(result.substring(0,result.length() - 3));
        
        //format date
        //String tampilan = "yyyy-MM-dd";
        //SimpleDateFormat format = new SimpleDateFormat(tampilan);
        //String tanggal = String.valueOf(format.format(txtTglTransaksi.getDate()));
        //lblTanggal.setText(tanggal);
        
        //if(txtKodeMembHidden.getText().equals("") || txtBeratHidden.getText().equals("") || txtHarga.getText().equals("") || txtJemputHidden.getText().equals("")){
        if(txtKodeMembHidden.getText().isEmpty() || txtBeratHidden.getText().isEmpty() || txtHarga.getText().isEmpty() || txtJemputHidden.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data list", "Input Gagal",JOptionPane.INFORMATION_MESSAGE); 
        }else{
            JOptionPane.showMessageDialog(null, "Data berhasil diproses", "Input Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
                        
        if (txtNmCust.getText().equals("") || txtHp.getText().equals("") || areaAlamat.getText().equals("") || txtJmlPcs.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Semua data harus terisi!", "Input Gagal",JOptionPane.INFORMATION_MESSAGE); 
            
            txtTglTransaksi.setDateFormatString("");
            cmbKodeCust.setSelectedIndex(0);
            txtNmCust.setText("");
            areaAlamat.setText("");            
            txtHp.setText("");
            txtJmlPcs.setText("");
            cmbLayanan.setSelectedIndex(0);
            cmbBerat.setSelectedIndex(0);
            txtHarga.setText("");
            txtEstAmbil.setDateFormatString("");
            cmbJemput.setSelectedIndex(0);
            txtTotal.setText("");
            txtTglTransaksi.requestFocus();
            
        }else{
        
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan", "Input Sukses",JOptionPane.INFORMATION_MESSAGE); 
        
        //output tabel data
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
            List list = new ArrayList<>();
            tabelData.setAutoCreateColumnsFromModel(true);
            //list.add(lblTanggal.getText());
            list.add(txtTglTransaksi.getDate());
            list.add(txtNmCust.getText());
            list.add(txtHp.getText());
            list.add(cmbLayanan.getSelectedItem().toString());
            list.add(jLabel4.getText());
            list.add(txtJmlPcs.getText() + " pcs");
            list.add(cmbJemput.getSelectedItem().toString());
            dataModel.addRow(list.toArray());
            Sum();
            
            //txtTglTransaksi.setDateFormatString("");
            cmbKodeCust.setSelectedIndex(0);
            txtNmCust.setText("");
            areaAlamat.setText("");            
            txtHp.setText("");
            txtJmlPcs.setText("");
            cmbLayanan.setSelectedIndex(0);
            cmbBerat.setSelectedIndex(0);
            txtHarga.setText("");
            jLabel3.setText("Rp 0,00");
            jLabel4.setText("Rp 0,00");
            //txtEstAmbil.setDateFormatString("");
            cmbJemput.setSelectedIndex(0);
            txtTotal.setText("");
            txtTglTransaksi.requestFocus();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void txtNmCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmCustActionPerformed

    private void txtJmlPcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlPcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlPcsActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
            txtTglTransaksi.setDateFormatString("");
            cmbKodeCust.setSelectedIndex(0);
            txtNmCust.setText("");
            areaAlamat.setText("");            
            txtHp.setText("");
            txtJmlPcs.setText("");
            cmbLayanan.setSelectedIndex(0);
            cmbBerat.setSelectedIndex(0);
            txtHarga.setText("");
            jLabel3.setText("Rp 0,00");
            jLabel4.setText("Rp 0,00");
            txtEstAmbil.setDateFormatString("");
            cmbJemput.setSelectedIndex(0);
            txtTotal.setText("");
            txtTglTransaksi.requestFocus();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void txtHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtHpActionPerformed

    private void txtHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHpKeyTyped
        // TODO add your handling code here:
        //HARUS ANGKA UNTUK NO HP lebih dari 6 digit dan kurang dari sama dengan 12
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtHp.getText().length() < 12 || (c == KeyEvent.VK_BACK_SPACE)|| (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
}

    }//GEN-LAST:event_txtHpKeyTyped

    private void txtJmlPcsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlPcsKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && txtJmlPcs.getText().length() < 2 || (c == KeyEvent.VK_BACK_SPACE)|| (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
          
    }//GEN-LAST:event_txtJmlPcsKeyTyped

    private void txtNmCustKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNmCustKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNmCustKeyTyped

    private void txtTglTransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTglTransaksiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglTransaksiFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAlamat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbBerat;
    private javax.swing.JComboBox<String> cmbJemput;
    private javax.swing.JComboBox<String> cmbKodeCust;
    private javax.swing.JComboBox<String> cmbLayanan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_data;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblBerat;
    private javax.swing.JLabel lblEstAmbil;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblJemput;
    private javax.swing.JLabel lblJmlPcs;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKodeCust;
    private javax.swing.JLabel lblLayanan;
    private javax.swing.JLabel lblNmCust;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTglTransaksi;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField txtBeratHidden;
    private com.toedter.calendar.JDateChooser txtEstAmbil;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtJemputHidden;
    private javax.swing.JTextField txtJmlPcs;
    private javax.swing.JTextField txtKodeMembHidden;
    private javax.swing.JTextField txtNmCust;
    private com.toedter.calendar.JDateChooser txtTglTransaksi;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void Sum() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel dataModel = (DefaultTableModel) tabelData.getModel();
        int jumlah = dataModel.getRowCount();
     
        jumlah_data.setText(Integer.toString(jumlah) + " rows");
    }
    }

